lakewood:
 regular:
  weekday: 110
  weekend: 90
 rewards:
  weekday: 80
  weekend: 80
 rate: 3
bridgewood:
 regular:
  weekday: 160
  weekend: 60
 rewards:
  weekday: 110
  weekend: 50
 rate: 4
ridgewood:
 regular:
  weekday: 220
  weekend: 150
 rewards:
  weekday: 100
  weekend: 40
 rate: 5
